name = "reki"
version = "1.2.0"

description = "A Gleam actor registry that manages actors by key, with fast ETS lookups and automatic cleanup"
licences = ["MIT"]
repository = { type = "github", user = "alii", repo = "reki" }
links = [{ title = "Repository", href = "https://github.com/alii/reki" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
